Change from NamedTuple to struct (with correct reflective equality) for DependencyKey
- Also fix printing bug for new DerivedKeys, and added input key
printing:
```julia
ERROR: SalsaDerivedException: Error encountered while executing Salsa derived function:
KeyError: key "Nathan" not found

------ Salsa Trace -----------------
[1] @input InputKey{Main.Salsa.InputMap{String,Float64}}(@0x0000000125e3ea40)[("Nathan",)]
[2] @derived letter_grade2(::Classroom4, "Nathan"::String)
------------------------------------

Stacktrace:
 [1] getindex at ./dict.jl:477 [inlined]
```